// Generated by nexus-rpc-gen. DO NOT EDIT!

import * as nexus from "nexus-rpc";

export const sayHelloService = nexus.service("SayHelloService", {
  mySyncOperation: nexus.operation<MyInput, MyOutput>({ name: "my_sync_operation" }),

  sayHello: nexus.operation<MyInput, MyOutput>({ name: "say_hello" }),
});

export interface MyInput {
  name: string;
}

export interface MyOutput {
  message: string;
}
