# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel
from nexusrpc import service, Operation


class MyInput(BaseModel):
    name: str


class MyOutput(BaseModel):
    message: str


@service
class SayHelloService:
    my_sync_operation: Operation[MyInput, MyOutput]

    say_hello: Operation[MyInput, MyOutput]
